#  kubectl apply -f doks-deploy.yaml

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vllm-server
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vllm-server
  template:
    metadata:
      labels:
        app: vllm-server
    spec:
      hostIPC: true
      tolerations:
      - key: CriticalAddonsOnly
        operator: Exists
      - key: amd.com/gpu
        operator: Exists
        effect: NoSchedule
      #imagePullSecrets:
      #  - name: rs-regcred
      containers:
      - name: vllm-container
        image: docker.io/richardxgf/amd:rocm7-rclone-gcs-001 # ROCm 7 for MI350X
        #imagePullPolicy: Always
        #command: ["sh","-c","sleep infinity"]
        ports:
        - containerPort: 8000
        env:
        - name: BUCKET
          value: "rs-validation-test"   # BUCKET   
        - name: FOLDER
          value: "test20251117/llama"   # PREFIX
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: MODEL
          value: meta-llama/Llama-3.1-8B-Instruct
        - name: GCS_JSON_FILE
          value: /app/gcs_access.json
        - name: GCS_REGION
          value: us-central1
        - name: HF_TOKEN
          valueFrom:
            secretKeyRef:
              name: rs-environment-variables
              key: HF_TOKEN
        resources:
          limits:
            amd.com/gpu: 8 # up to 8
        volumeMounts:
        - name: gcs-access
          mountPath: /app/gcs_access.json
          subPath: gcs_access.json        # subPath ensures the file inside the Secret is mounted as /app/gcs_access.json rather than as a directory.
        - name: temp-hf-cache
          mountPath: /root/.cache/huggingface
        - name: shm
          mountPath: /dev/shm
        - name: dev-kfd
          mountPath: /dev/kfd
        - name: dev-dri
          mountPath: /dev/dri
        securityContext:
          capabilities:
            add:
            - SYS_PTRACE
          seccompProfile:
            type: Unconfined
      securityContext:
        supplementalGroups:
        - 44  
      volumes:
      - name: gcs-access
        secret:
          secretName: gcs-access
      - name: temp-hf-cache
        hostPath:
          path: /root/.cache/huggingface
          type: DirectoryOrCreate
      - name: shm
        emptyDir:
          medium: Memory
      - name: dev-kfd
        hostPath:
          path: /dev/kfd
      - name: dev-dri
        hostPath:
          path: /dev/dri
